---
version: "3.8"
services:
  movies:
    image: bhumikalahari/moviespay:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: bhumikalahari/trainpay:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: bhumikalahari/dthpay:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: bhumikalahari/rechargepay:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
